version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ghostscript-rust"
s3_prefix = "ghostscript-rust"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wfca8h0xqncn"
